# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='datehired',
            field=models.DateField(),
        ),
    ]
