# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mylogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('FK_addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_adedby', to='mylogin.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('FK_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_item', to='wishapp.Item')),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_user', to='mylogin.Users')),
            ],
        ),
    ]
